services:
  crossroad:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: crossroad
    restart: unless-stopped
    working_dir: /app # Should match WORKDIR in Dockerfile
    volumes:
      # Mount the jobOut directory for persistent storage of job results
      - ./jobOut:/app/jobOut
    ports:
      - "8000:8000" # Map port 8000 of the container to port 8000 on the host
    labels:
      # --- Define the middleware for request body limit ---
      - "traefik.http.middlewares.crossroad-bodylimit.buffering.maxRequestBodyBytes=209715200" # 200MB

      # --- Attach the middleware to Dokploy's existing HTTP router ---
      # The existing middleware is redirect-to-https@file. We prepend ours.
      - "traefik.http.routers.pranjalwork-crossroad-backend-kysfxf-28-web.middlewares=crossroad-bodylimit@docker,redirect-to-https@file"

      # --- Attach the middleware to Dokploy's existing HTTPS router ---
      - "traefik.http.routers.pranjalwork-crossroad-backend-kysfxf-28-websecure.middlewares=crossroad-bodylimit@docker"

      # --- Add Timeouts to the HTTPS Service ---
      # Service name used by Dokploy for the HTTPS router: pranjalwork-crossroad-backend-kysfxf-28-websecure
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-websecure.loadbalancer.server.forwardingTimeouts.dialTimeout=30s"
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-websecure.loadbalancer.server.forwardingTimeouts.responseHeaderTimeout=300s" # Increased for potentially long processing
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-websecure.loadbalancer.server.forwardingTimeouts.idleConnTimeout=300s"     # Increased

      # --- Add Timeouts to the HTTP Service (for completeness, though requests should redirect) ---
      # Service name used by Dokploy for the HTTP router: pranjalwork-crossroad-backend-kysfxf-28-web
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-web.loadbalancer.server.forwardingTimeouts.dialTimeout=30s"
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-web.loadbalancer.server.forwardingTimeouts.responseHeaderTimeout=300s"
      - "traefik.http.services.pranjalwork-crossroad-backend-kysfxf-28-web.loadbalancer.server.forwardingTimeouts.idleConnTimeout=300s"
