services:
  crossroad:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: crossroad
    restart: unless-stopped
    working_dir: /app # Should match WORKDIR in Dockerfile
    volumes:
      # Mount the jobOut directory for persistent storage of job results
      - ./jobOut:/app/jobOut
    ports:
      - "8000:8000" # Map port 8000 of the container to port 8000 on the host
    environment:
      # These environment variables will be passed to the container
      # Dokploy/Coolify might override or manage these through their UI
      - CROSSROAD_ROOT=/app
      - CORS_ALLOWED_ORIGINS=https://crossroad.bioinformaticsonline.com,https://cr.pranjal.work,https://cw.pranjal.work,http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173
