services:
  crossroad:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    # container_name: crossroad # REMOVED to prevent Traefik default router/service conflicts
    restart: unless-stopped
    working_dir: /app # Should match WORKDIR in Dockerfile
    volumes:
      # Mount the jobOut directory for persistent storage of job results
      - ./jobOut:/app/jobOut
    ports:
      - "8000:8000" # Map port 8000 of the container to port 8000 on the host
