services:
  crossroad:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: crossroad
    restart: unless-stopped
    working_dir: /app # Should match WORKDIR in Dockerfile
    volumes:
      # Mount the jobOut directory for persistent storage of job results
      - ./jobOut:/app/jobOut
    ports:
      - "8000:8000" # Map port 8000 of the container to port 8000 on the host
    labels:
      # --- Middleware for Request Body Limit ---
      # Define the middleware
      - "traefik.http.middlewares.crossroad-bodylimit.buffering.maxRequestBodyBytes=209715200" # 200MB, adjust as needed

      # --- Apply Middleware to Routers ---
      # Apply to the HTTP router (if you want to allow large uploads over HTTP before redirect)
      # Dokploy's generated router name for HTTP is: pranjalwork-crossroad-backend-kysfxf-28-web
      - "traefik.http.routers.pranjalwork-crossroad-backend-kysfxf-28-web.middlewares=crossroad-bodylimit@docker,redirect-to-https@file"

      # Apply to the HTTPS router
      # Dokploy's generated router name for HTTPS is: pranjalwork-crossroad-backend-kysfxf-28-websecure
      - "traefik.http.routers.pranjalwork-crossroad-backend-kysfxf-28-websecure.middlewares=crossroad-bodylimit@docker"
