version: '3.8'

services:
  crossroad:
    image: condaforge/mambaforge:latest
    container_name: crossroad
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - ./jobOut:/app/jobOut
    ports:
      - "9095:8000"
    environment:
      - CROSSROAD_ROOT=/app
      - CORS_ALLOWED_ORIGINS=https://crossroad.bioinformaticsonline.com,https://cr.pranjal.work,https://cw.pranjal.work,http://localhost:3000,http://localhost:5173
    command: >
      /bin/bash -c "
        echo '--- Starting CrossRoad Service Setup (service name: crossroad) ---' &&
        echo 'Current directory in container: $(pwd)' &&
        echo 'Listing /app directory contents:' &&
        ls -la /app &&
        echo 'Attempting to install dependencies via Mamba...' &&
        mamba install -y -c jitendralab -c bioconda -c conda-forge python=3.12 crossroad pyarrow pandas fastapi uvicorn &&
        echo 'Mamba installation complete.' &&
        echo 'Starting Uvicorn server for crossroad.api.main:app on 0.0.0.0:8000...' &&
        uvicorn crossroad.api.main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - dokploy-network
    labels:
      # --- Traefik Middleware for Request Body Limit ---
      - "traefik.http.middlewares.crossroad-bodylimit.buffering.maxRequestBodyBytes=209715200" # 200MB
      - "traefik.http.middlewares.crossroad-bodylimit.buffering.memRequestBodyBytes=209715200" # 200MB

      # --- Apply Middleware to Traefik Router ---
      # Apply the body limit middleware to the HTTPS router for cr.pranjal.work.
      # The router name 'pranjalwork-crossroad-backend-kysfxf-secure' is confirmed by Traefik logs.
      # If this router already has other middlewares assigned by Dokploy,
      # you would append ',crossroad-bodylimit@docker' to the existing list.
      - "traefik.http.routers.pranjalwork-crossroad-backend-kysfxf-secure.middlewares=crossroad-bodylimit@docker"

      # Enable Traefik for this service (Dokploy usually handles this, but good to be explicit)
      - "traefik.enable=true"
      # REMOVED: Explicit traefik.http.services... label to avoid conflict

networks:
  dokploy-network:
    external: true