{% set name = "crossroad" %}
{% set version = "0.1.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b2/15/2036298fbb7392c8938632a973e3e63bda247ce96b3069017d33e7d9662a/crossroad_cli-0.1.4.tar.gz
  sha256: 21a02bfd9ea43743c00fa3377fa83e2397cbb00799866e47d5f21cfa432e20bd

build:
  noarch: python  # Add this line to make it platform-independent
  number: 0
  script: |
    $PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir
  entry_points:
    - crossroad = crossroad.cli.main:main
  preserve_egg_dir: False
  skip: True  # [win]  # You can actually remove this line since noarch handles platform skipping

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    # Add build-time dependencies that match setup.py
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
  run:
    - python
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - bioconda::minimap2
    - pranjalpruthi::perf_ssr
    - pip

test:
  imports:
    - crossroad
    - crossroad.cli
    - crossroad.api
    - crossroad.core
  commands:
    - crossroad --help
  requires:
    - python
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - bioconda::minimap2

about:
  home: https://github.com/pranjalpruthi/crossroad
  license: MIT
  license_family: MIT
  summary: 'A tool for analyzing SSRs in genomic data'
  description: |
    Crossroad is a comprehensive tool for analyzing Simple Sequence Repeats (SSRs) 
    in genomic data, developed at CSIR-IGIB.
  doc_url: https://github.com/pranjalpruthi/crossroad
  dev_url: https://github.com/pranjalpruthi/crossroad

extra:
  recipe-maintainers:
    - pranjalpruthi
