{% set name = "crossroad" %}
{% set version = "0.2.2" %}
{% set python_min = "3.8" %}
{% set numpy_version = "1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/1e/2e/48c69abc1e3a72a73b7f29a823a602278449fe88221211bb169d63d9f3cf/crossroad_cli-0.2.2-py3-none-any.whl
  sha256: 1c14821b27eae2c6f5e23d314d7974c9dcbee95500f8e814bc38009693aa411d  # This is the SHA256 of the wheel file

build:
  noarch: python
  number: 0
  script: |
    pip install --no-deps --ignore-installed --no-cache-dir crossroad_cli-{{ version }}-py3-none-any.whl
  entry_points:
    - crossroad = crossroad.cli.main:main
  preserve_egg_dir: False

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy {{ numpy_version }}
    - pandas
    - plotly

  run:
    - python
    - numpy {{ numpy_version }}
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
    - plotly
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - pranjalpruthi::perf_ssr
    - jitendralab::plotly-upset-hd
    - typer
    - rich-click
    - argcomplete

test:
  imports:
    - crossroad
    - crossroad.cli
    - crossroad.api
    - crossroad.core
    - crossroad.core.plots
    - plotly
    - plotly_upset
  commands:
    - crossroad --help
  requires:
    - python
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools

about:
  home: https://github.com/pranjalpruthi/crossroad
  license: MIT
  license_family: MIT
  summary: 'A tool for analyzing SSRs in genomic data'
  description: |
    Crossroad is a comprehensive tool for analyzing Simple Sequence Repeats (SSRs)
    in genomic data, developed at CSIR-IGIB. Includes various plotting utilities.
  doc_url: https://github.com/pranjalpruthi/crossroad
  dev_url: https://github.com/pranjalpruthi/crossroad

extra:
  recipe-maintainers:
    - pranjalpruthi
