{% set name = "crossroad" %}
{% set version = "0.1.5" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/0e/8c/59e3d350e449e2e0e4cbf81a65cf628deb72260bb2c4040078e7e6071a71/crossroad_cli-0.1.5.tar.gz
  sha256: e6a350468327c2c4b8ae955c29b69252d61aa3536ccb0113505616a7fd3ce551

build:
  noarch: python  # Add this line to make it platform-independent
  number: 0
  script: |
    $PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir
  entry_points:
    - crossroad = crossroad.cli.main:main
  preserve_egg_dir: False
  skip: True  # [win]  # You can actually remove this line since noarch handles platform skipping

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    # Add build-time dependencies that match setup.py
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
  run:
    - python
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - pranjalpruthi::perf_ssr
    - pip

test:
  imports:
    - crossroad
    - crossroad.cli
    - crossroad.api
    - crossroad.core
  commands:
    - crossroad --help
  requires:
    - python
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools

about:
  home: https://github.com/pranjalpruthi/crossroad
  license: MIT
  license_family: MIT
  summary: 'A tool for analyzing SSRs in genomic data'
  description: |
    Crossroad is a comprehensive tool for analyzing Simple Sequence Repeats (SSRs) 
    in genomic data, developed at CSIR-IGIB.
  doc_url: https://github.com/pranjalpruthi/crossroad
  dev_url: https://github.com/pranjalpruthi/crossroad

extra:
  recipe-maintainers:
    - pranjalpruthi
