package:
  name: crossroad
  version: "0.3.6"

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - crossroad = crossroad.cli.main:app
  preserve_egg_dir: false

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - numpy 
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
    - plotly
    - python-kaleido >=0.1.0,<0.3 
    - pyarrow 
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - jitendralab::perf_ssr
    - jitendralab::plotly-upset-hd
    - rich 
    - rich-argparse
    - typer        
    - rich-click >=1.7.0 
    - argcomplete       
    - upsetplot 
    - python-dotenv

test:
  imports:
    - crossroad
  commands:
    - crossroad --help
  requires:
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools

about:
  home: https://github.com/pranjalpruthi/crossroad
  license: MIT
  license_family: MIT
  summary: 'A tool for analyzing SSRs in genomic data'
  description: |
    Crossroad is a comprehensive tool for analyzing Simple Sequence Repeats (SSRs)
    in genomic data, developed at CSIR-IGIB. Includes various plotting utilities.
  doc_url: https://github.com/pranjalpruthi/crossroad
  dev_url: https://github.com/pranjalpruthi/crossroad

extra:
  recipe-maintainers:
    - pranjalpruthi
