context:
  name: crossroad
  version: 0.3.3
  python_min: '3.9' # Updated Python requirement

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: dist/crossroad_cli-{{ version }}-py3-none-any.whl
  sha256: 9a0c90daec49b7c660d879969029cc32afa6c2492e649cc7ceca380d001ba52c

build:
  noarch: python
  number: 0
  script: |
    pip install --no-deps --ignore-installed --no-cache-dir crossroad_cli-{{ version }}-py3-none-any.whl
  entry_points:
    - crossroad = crossroad.cli.main:app
  preserve_egg_dir: false

requirements:
  host:
    - 'python {{ python_min }}'
    - pip
    - setuptools
    - numpy # Keep numpy here for build host
    - pandas
    - plotly

  run:
    - python {{ python_min }}.* # Pin Python version
    - numpy # Keep numpy here for runtime
    - fastapi
    - uvicorn
    - python-multipart
    - pandas
    - pydantic
    - requests
    - plotly
    - pyarrow # <-- Add pyarrow here
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools
    - jitendralab::perf_ssr
    - jitendralab::plotly-upset-hd
    - rich # Added rich for TUI/logging
    - rich-argparse
    - typer        # Typer CLI framework (replaced typer[all] with plain typer)
    - rich-click >=1.7.0 # Rich-enhanced Click help (Updated version)
    - argcomplete       # Shell tab-completion
    - upsetplot # <-- Add upsetplot here

test:
  imports:
    - crossroad
    - crossroad.cli
    - crossroad.api
    - crossroad.core
    - crossroad.core.plots
    - plotly
    - plotly_upset
  commands:
    - crossroad --help
  requires:
    - python {{ python_min }}.* # Pin Python version for tests
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::bedtools

about:
  home: https://github.com/pranjalpruthi/crossroad
  license: MIT
  license_family: MIT
  summary: 'A tool for analyzing SSRs in genomic data'
  description: |
    Crossroad is a comprehensive tool for analyzing Simple Sequence Repeats (SSRs)
    in genomic data, developed at CSIR-IGIB. Includes various plotting utilities.
  doc_url: https://github.com/pranjalpruthi/crossroad
  dev_url: https://github.com/pranjalpruthi/crossroad

extra:
  recipe-maintainers:
    - pranjalpruthi
