name: Conda Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.10
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: base # Activate base env where boa will be installed
          channels: conda-forge,bioconda,jitendralab,defaults # Add channels here for consistency

      - name: Install build dependencies
        shell: bash -el {0} # Ensure conda is activated
        run: |
          mamba install -c conda-forge boa conda-build conda-verify anaconda-client --yes

      - name: Build Conda Package
        shell: bash -el {0} # Ensure conda is activated
        run: |
          boa build recipe.yaml
          
      - name: Upload to Anaconda
        shell: bash -el {0} # Ensure conda is activated
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda upload --force -u jitendralab ${{ env.CONDA_PREFIX }}/conda-bld/**/crossroad-*.tar.bz2 