name: Conda Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Mamba
        run: |
          curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
          bash Mambaforge-$(uname)-$(uname -m).sh -b
          source ~/mambaforge/etc/profile.d/conda.sh
          conda activate base
          mamba install -c conda-forge boa conda-build conda-verify anaconda-client
          
      - name: Build Conda Package
        run: |
          source ~/mambaforge/etc/profile.d/conda.sh
          conda activate base
          boa build recipe.yaml
          
      - name: Upload to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          source ~/mambaforge/etc/profile.d/conda.sh
          conda activate base
          anaconda upload --force -u jitendralab /Users/runner/mambaforge/conda-bld/noarch/crossroad-*.tar.bz2 